version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=app
      - POSTGRES_DATABASE=app
